[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
target_version = ["py310"]

[tool.isort]
profile = "black"

[tool.mypy]
exclude = '''
(?x)(
    build
    | dist
  )

'''
